#!/bin/bash

set -eo pipefail

# Deploy code from the Dev environment to Test
terminus env:deploy $TERMINUS_SITE.test --note "Autodeploy from Circle" --yes

# Run updatedb on the dev environment
terminus -n drush $TERMINUS_SITE.test -- updatedb --yes

# If there are any exported configuration files, then import them
if [ -f "config/system.site.yml" ] ; then
  terminus -n drush "$TERMINUS_SITE.test" -- config-import --yes
fi

terminus -n drush "$TERMINUS_SITE.test" -- cache-rebuild
